baseURL: "https://iamlaksh1.github.io/crops-n-leaves/"
languageCode: en-us
title: Lakshmanan Venkatesan
theme: PaperMod
ignoreErrors: ["error-remote-getjson"] 

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true


menu:
  main:
    - name: Posts
      pageRef: /posts/
      weight: 2 
    - identifier: GitHub
      name: GitHub
      url: "https://github.com/iamlaksh1"
      weight: 3